[package]
name = "netpeek"
version = "0.1.0"
edition = "2024"

[dependencies]
trust-dns-resolver = "0.23"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
humantime = "2"
