[package]
name = "procwatch"
version = "0.1.0"
edition = "2024"

[dependencies]
procfs = "0.16"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
humantime = "2"
