[package]
name = "netcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
humantime = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
